[project]
name = "mirrulations-hive-partitioned-parquet"
version = "0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb",
    "ipykernel",
    "python-dotenv",
]
